const Data = {
    productItems: [
      {
        id: 1,
        discount: 30,
        cover: "./images/flash/flash-1.png",
        name: "Adidas Shoes",
        price: 200,
      },
      {
        id: 2,
        discount: 10,
        cover: "./images/flash/flash-2.png",
        name: "Watch Classic",
        price: 250,
      },
      {
        id: 3,
        discount: 5,
        cover: "./images/flash/flash-3.png",
        name: "Samsung Galaxy M13",
        price: 2000,
      },
      {
        id: 4,
        discount: 10,
        cover: "./images/flash/flash-4.png",
        name: "Smart Watch Black",
        price: 400,
      },
      {
        id: 5,
        discount: 15,
        cover: "./images/flash/flash-5.png",
        name: "Glasses Unisex",
        price: 100,
      },
      {
        id: 6,
        discount: 50,
        cover: "./images/flash/flash-6.png",
        name: "Smart Watch Black",
        price: 150,
      },
      {
        id: 7,
        discount: 5,
        cover: "./images/flash/flash-7.png",
        name: "Samsung Machine A Laver",
        price: 5000,
      },
      {
        id: 8,
        discount: 10,
        cover: "./images/flash/flash-8.png",
        name: "Shoes Nike",
        price: 300,
      },
      {
        id: 9,
        discount: 10,
        cover: "./images/flash/flash-9.png",
        name: "Hoddy",
        price: 280,
      },
      {
        id: 10,
        discount: 5,
        cover: "./images/flash/flash-10.png",
        name: "Glasses",
        price: 340,
      },
      {
        id: 11,
        discount: 0,
        cover: "./images/flash/flash-11.png",
        name: "Ball ",
        price: 109,
      },
      {
        id: 12,
        discount: 20,
        cover: "./images/flash/flash-12.png",
        name: "Goalkeeper Glove",
        price: 209,
      },
    ],
  }
  export default Data
  